version: '3'

services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile.php7
    ports:
      - "${WEBPORT}:80"
    volumes:
      - ./html:/var/www/html
      - php-logs:/var/log/apache2
    links:
      - db
      #- pdb

  db:
    build:
      context: .
      dockerfile: Dockerfile.mariadb
    ports:
      - "${DBPORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpw
      - MYSQL_DATABASE=lampserver
      - MYSQL_USER=phpuser
      - MYSQL_PASSWORD=phppw
    volumes:
      - ./mysql:/var/lib/mysql
  
  pdb:
    image: postgres
    restart: always
    ports:
      - "${PDBPORT}:5432"
    environment:
      POSTGRES_PASSWORD: example
    environment:
      - POSTGRES_DB=pgdb
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pguserpw
    volumes:
      - ./pgsql:/var/lib/postgresql/data
  
  adminer:
    image: adminer
    restart: always
    ports:
      - "${ADMINDERPORT}:8080"
    links:
      - db
      - pdb
      
  elk:
    image: willdurand/elk
    ports:
      - "${ELKPORT}:80"
    volumes:
      - ./elk/logstash:/etc/logstash
      - ./elk/logstash/patterns:/opt/logstash/patterns
      - php-logs:/var/log/apache2

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "${MAILHOGPORT}:8025"

volumes:
  php-logs:
